---
title: "FAIR2-PIT-UN Teaching Materials"
output: html_document
---

```{css, echo=FALSE}
.navbar-default {
    background-color: #123271;
    border-color: #123271;
}

```


Welcome to **Centering the Public Interest in Integrated Administrative Data Analytics**.
Integrated Administrative Data Systems (IDS) are among our most powerful tools to guide decision making for social good. By linking records across health, housing, education, and social services we can start to understand the complex challenges that poverty and marginalization carry.

But data is not a neutral mirror of reality; it is a product of human systems. Without a framework that accounts for the insights of those represented in the data, even the most sophisticated analytics can inadvertently perpetuate bias and mask systemic inequality.


This curriculum, supported by the Public Interest Technology University Network (PIT-UN), is designed to bridge the gap between administrative data and lived experience and between those working on data analytics and those working on the ground to drive positive social change. 

Through the five modules below, you will learn to apply the **FAIR2 framework**, moving beyond technical data standards to **Frame** data with community knowledge, **Articulate** this knowledge as assumptions in a causal map, **Identify** hidden biases, and **Report** back to the communities represented in the data.

Join us in enhancing the power of linked administrative data with community knowledge to serve the public interest!

<br>

### Module 1: FAIR2 Framework

* An introduction to the Frame-Articulate-Identify-Report framework. Learn how to integrate community knowledge and structural context into the foundation of your data science projects.

  * [Slide presentation](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/raw/refs/heads/main/Module%201_FAIR2_12.9.25.pptx)

<br>


### Module 2: Demographic Data & Data Chats

* This module introduces FAIR2 Data Chats as a method to elicit the experiential knowledge necessary to interpret administrative records and guide data analytics. It also explores how race and gender data differences across and within administrative systems can be addressed to reduce discrimination bias. 

  * [Slide presentation](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/raw/refs/heads/main/Module_2_R&G%20in%20IDS_Data%20Chat_WITH%20AUDIO.pptx)
  
<iframe width="711" height="400" src="https://www.youtube.com/embed/ddugtHeTh68" title="Module 2: Race and Gender Data Chat Findings" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


<br>


### Module 3: Label Bias in IDS Analytics

* Not everything that matters is measured. Learn to identify Label Bias, where administrative proxies (like shelter use) are used to represent complex human outcomes (like homelessness).


  * [Slide presentation](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/raw/refs/heads/main/Module_3_Label%20bias.pptx)
  * [Simulation example](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/blob/main/Labels-bias.Rmd)

<iframe width="711" height="400" src="https://www.youtube.com/embed/K60RDF-VhuE" title="Module 3: Label Bias" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


<br>


### Module 4: Collider Bias

* Here we see how administrative data is prone to what is called collider bias and how ignoring the selection process of people represented in administrative data can create statistical illusions that mask discrimination.

  * [Slide presentation](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/raw/refs/heads/main/Module_4_Collider%20bias_2026.pptx)
  * [Simulation example](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/blob/main/Collider-bias.Rmd)

<br>


### Module 5: Recommendations for Social Change

* This final module provides strategies for social workers and data practitioners to advocate for better data intake, more precise research questions, and the ethical dissemination of findings. 

  * [Slide presentation](https://github.com/PovertyCenterCLE/FAIR2-PIT-UN/raw/refs/heads/main/Module_5_Recommendations%20to%20address%20constraints%20and%20bias%20in%20IDS_fgcr.pptx)

<iframe width="711" height="400" src="https://www.youtube.com/embed/MazHZUf4MIQ" title="Module 5: Recommendations" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

  

<br>
<br>
<br>


